### ISSUE TITLE
How to connect a VID28 with 4 Pins?

### ISSUE THREAD

**Issue by s256** [GewoonGijs/VID28#4]
Hi,
beginner here. I have a VID28-05 / BKA30D-R5 motor and I am using an ESP32.
The motor has 4 connectors, your code only offers 3 pins, am I still able to use the motor with you lib?

If so, can you give me a quick hint how to do so?

Best
s256

**Comment by GewoonGijs** [comment]
Hi there,

Nice you want to use my library. Sorry I haven’t documented it in the README, but in de MotorVID28.c I explain how to connect:

//
//
// The VID29 is a 6 state stepper motor. Pin 2 and 3 of the stepper motor
// are high and low simultaneously. So they share one IO pin.
//
// Note: to use microsteps we need to assing PWM capable outputs
//
//

Succes!!!

P.S. What are you going to build?

-- 
Gijs Withagen

**Comment by s256** [comment]
Thanks for the quick answer. 
I'll give it a try!

It's in german but this is basically the project: https://forum.zusi.de/viewtopic.php?f=25&t=13044&p=311390

So using two BKA30D-R5 basically for a pressure gauge as part of a train simulator. 

Did you run you lib on an ESP32? Some other projects regarding VID29 had some issues when running on an ESP32. I'm new to this (ESP32 and Steppermotors). What I didn't find out yet is the difference between a VID29 and VID28 stepper motor.
