### ISSUE TITLE
Pin connection?

### ISSUE THREAD

**Issue by leongwaikay** [GewoonGijs/VID28#5]
The README says:
>N.B. The motors do have four pins, but from the datasheet it can be seen that **pin 2 and 3** are simultaneously high and low during the complete step cycle. Therefore i did connet **pin 3 and 4** of the motor to the same I/O pin on the Arduino.

Shouldn't it be connecting pin 2 and 3 to the same I/O pin?

The VID28 datasheet has labelled pins 1, 2, 3, 4. What should the corresponding pins be mapped in the MotorVID28 constructor? Also why is pin1 not unsigned?

**Comment by GewoonGijs** [comment]
You are right, pin 2 and 3 should be connected to the same Arduino output pin. 

Verstuurd vanaf mijn iPhone
